spring.application.name=big-basket-server

server.port=5000

spring.datasource.url=jdbc:h2:mem:mydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


# Ensure schema + data.sql runs
spring.sql.init.mode=always

# Important for JPA + data.sql order( it is to make sure first tables creates and then data.sql execution
spring.jpa.defer-datasource-initialization=true
